# Generated by Django 3.2.5 on 2021-10-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='image_location',
            field=models.CharField(default='Whire location image was taken', max_length=50),
        ),
        migrations.AddField(
            model_name='photos',
            name='image_name',
            field=models.CharField(default='White name of image', max_length=100),
        ),
    ]
